### ISSUE TITLE
.parse_range allows for earlier dates, such as '-2100 - -2000'

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/parse_date#31]
I can't think of a good reason NOT to allow dates earlier than -999.

DLME using .parse_range for American Numismatic Society gets this error:

```
    Record: http://numismatics.org/collection/1913.91.1,"Clay Tablet, Mesopotamia, 2100 BC - 2000 BC. 1913.91.1",1913.91.1,,,,,,,Islamic,,,,,,,,,manuscript,Clay,,𒐊𒂆𒆬𒌓/ 𒂍𒁮𒃼𒋫/ 𒈧𒁮𒃼𒂷𒂷𒉈/ 𒈬𒈾𒊏𒌓𒁺/ 𒈬𒎙𒄰𒐈𒂆𒆬/𒈠𒊏𒀭𒋧/ 𒐁𒐈𒊺𒄥𒈗/ 𒊺𒀀𒊮𒊕𒆕/ 𒂍𒍣𒉌𒍝𒋫𒋗/𒁀𒊏𒀭𒋢𒁍/ 𒐀𒄥𒀀𒇒𒉚𒈨𒋧[𒈬𒁕]𒄰,,Tablet,,,Mesopotamia,𒀀𒀀𒆗𒆷/ 𒌉𒅇𒈠𒉌/ 𒋗𒁀𒋾/ 𒈫𒌆𒃻𒇴/ 𒆬𒁉𒁹𒂆𒆬/ 𒁹𒍏𒊺𒌴/ 𒆠𒇲𒌋𒂆𒍏/ 𒈬𒁺𒌓𒐌𒄰𒁉/𒅎/ 𒆕𒀀{𒁉}𒁉/ 𒆠𒈗𒆬𒂵𒉌/𒋫/ 𒌑𒌆𒃶𒁺/ 𒋗𒁀𒋾,,,-2100|-2000,http://numismatics.org/collectionimages/19001949/1913/1913.91.1.obv.width175.jpg,http://numismatics.org/collectionimages/19001949/1913/1913.91.1.rev.width175.jpg,2016-10-21T21:48:00Z

    Exception: ParseDate::Error: Unable to parse range from '-2100 - -2000': undefined method `>' for nil:NilClass
    /usr/local/bundle/gems/parse_date-0.3.1/lib/parse_date.rb:49:in `rescue in parse_range'
    Caused by
    NoMethodError: undefined method `>' for nil:NilClass
    /usr/local/bundle/gems/parse_date-0.3.1/lib/parse_date.rb:58:in `year_range_valid?'

[ERROR] Unable to parse range from '-2100 - -2000': undefined method `>' for nil:NilClass
2019-10-22T20:42:12+00:00 ERROR Unexpected error on record <record #1 (data/american-numismatic-society/islamic-department/data/numismatic_islam_department.csv #1), output_id:ans_1944-100-73346>
    while executing (to_field "cho_date_range_norm2" at traject_configs/numismatic_csv_config.rb:43)

    Record: http://numismatics.org/collection/1944.100.73346,"Clay Tablet, Mesopotamia, 2100 BC - 2000 BC. 1944.100.73346",1944.100.73346,,,,,,,Islamic,,,,,,,,,manuscript,Clay,,,,Tablet,,,Mesopotamia,,,,-2100|-2000,http://numismatics.org/collectionimages/19001949/1944/1944.100.73346.obv.width175.jpg,http://numismatics.org/collectionimages/19001949/1944/1944.100.73346.rev.width175.jpg,2016-10-21T21:57:27Z

    Exception: ParseDate::Error: Unable to parse range from '-2100 - -2000': undefined method `>' for nil:NilClass
    /usr/local/bundle/gems/parse_date-0.3.1/lib/parse_date.rb:49:in `rescue in parse_range'
    Caused by
    NoMethodError: undefined method `>' for nil:NilClass
    /usr/local/bundle/gems/parse_date-0.3.1/lib/parse_date.rb:58:in `year_range_valid?'
```

**Comment by ndushay** [comment]
Also, from openn/penn-0001:  '502-504'

```
    Exception: ParseDate::Error: Unable to parse range from '502-504': undefined method `>' for nil:NilClass
    /usr/local/bundle/gems/parse_date-0.3.1/lib/parse_date.rb:49:in `rescue in parse_range'
    Caused by
    NoMethodError: undefined method `>' for nil:NilClass
    /usr/local/bundle/gems/parse_date-0.3.1/lib/parse_date.rb:58:in `year_range_valid?'

[ERROR] Unable to parse range from '502-504': undefined method `>' for nil:NilClass
/usr/local/bundle/gems/parse_date-0.3.1/lib/parse_date.rb:49:in `rescue in parse_range': Unable to parse range from '502-504': undefined method `>' for nil:NilClass (ParseDate::Error)
	from /usr/local/bundle/gems/parse_date-0.3.1/lib/parse_date.rb:42:in `parse_range'
	from /opt/traject/lib/macros/date_parsing.rb:34:in `block (2 levels) in parse_range'
	from /opt/traject/lib/macros/date_parsing.rb:33:in `each'
	from /opt/traject/lib/macros/date_parsing.rb:33:in `block in parse_range'
	from /usr/local/bundle/gems/traject-3.2.0/lib/traject/indexer/step.rb:138:in `block in execute'
```
